name: Analyze code statically
"on": pull_request
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Analyze code statically using ESLint
        uses: moneyforward/eslint-action@v0
